default-mode:
  add:
  remove: [pull_request_target, issues]
comments:
  - name: Check Link
    url_mode: deny
    url_list:
      - hostname: ^(?:.+\.)?github\.com$
        pathname: ^/MaaAssistantArknights/
      - hostname: ^(?:.+\.)?maa\.plus$
        search: ^\?debug=1
      - hostname: ^(?:.+\.)?prts\.plus$
    content: "> [!warning]\n存在未确认的链接，请谨慎访问。\n\
      There are unconfirmed links, please visit with caution.\n\n${body}"
    mode: update
  - name: Hide gcc
    regexes: "(?=.*(changeme|gcc))"
    content: "> [!Caution]\n该评论中的链接文件含有病毒，请勿下载。\n\
      The file linked in this comment contain a virus. Please do not download it.\n\n${body}"
    mode: update
